networks:
  netb3:
   driver: bridge

services:
  b3api: #Api
    container_name: b3api-ctn
    hostname: b3api
    image: ${DOCKER_REGISTRY-}b3api-img
    build:
      context: .
      dockerfile: src/B3.Api/Dockerfile
    ports: 
     - "8081:8080"
    networks:
     - netb3

  b3app: #App
    container_name: b3app-ctn
    hostname: b3app
    image: ${DOCKER_REGISTRY-}b3app-img
    build:
      context: .
      dockerfile: src/B3.App/Dockerfile
    volumes:
     - ./src/B3.App/nginx.conf:/etc/nginx/nginx.conf
    ports: 
     - "3003:80"
    depends_on:
     - b3api
    networks:
     - netb3

   